openapi: 3.0.0
info:
  version: 1.0.0
  title: LCD API
  description: >-
    API para obtener la representación de números en LCD
  contact:
    name: Jesús
    email: jesapaort@alum.us.es
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /api/v1/numbers:
    options:
      summary: CORS support
      operationId: corsSupport
      description: |
        Enable CORS by returning correct headers
      tags:
        - CORS
      responses:
        200:
          description: Default response for CORS method
    post:
      description: Genera los números dados en formato LCD con un tamaño dado
      operationId: convertToLCD
      requestBody:
        x-name: Numbers
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Numbers"
        description: Numeros con tamaño determinado a transformar a LCD
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LCDnumbers"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    LCDnumbers:
      type: array
      minItems: 1
      items:
        type: string
    Numbers:
      type: array
      minItems: 1
      items:
        type: object
        required:
          - t
          - n
        properties:
          t:
            type: integer
          n:
            type: integer